implementation/tool_sharing/manage_tools/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^review_review/(?P<pk>[0-9]+)/$', views.review_review, name="review_review"),
    url(r'^my_tools/$', views.my_tools, name="my_tools"),
    url(r'^new_tool/$', views.new_tool, name="new_tool"),
    url(r'^get_reviews/(?P<pk>[0-9]+)/$', views.get_reviews, name="get_reviews"),
    url(r'^post_review/(?P<pk>[0-9]+)/$', views.post_review, name="post_review"),
    url(r'^edit_tool/(?P<pk>[0-9]+)/$', views.edit_tool, name="edit_tool"),
    url(r'^remove_tool/(?P<pk>[0-9]+)/$', views.remove_tool, name="remove_tool"),
    url(r'^update_status/(?P<pk>[0-9]+)/$', views.update_status, name="update_status"),
    url(r'^available_reviews/$', views.available_reviews, name="available_reviews"),
]

implementation/tool_sharing/tool_listing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='tool_listing'),
    url(r'^(?P<id>[0-9]+)/$', views.tool_detail, name='tool_detail'),
]

implementation/tool_sharing/tool_sharing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from user.views import sign_in, log_out


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^sign_in/$', sign_in, name="sign_in"),
    url(r'^log_out/$', log_out, name="log_out"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^manage_tools/', include('manage_tools.urls', namespace="manage_tools", app_name='manage_tools')),
    url(r'^account/', include('user.urls', namespace='user', app_name='user')),
    # the tool listing urls
    url(r'^tools/', include('tool_listing.urls', namespace='tool_listing', app_name='tool_listing')),
    # shed creating
    url(r'^shared_zone/', include('shared_zone.urls', namespace='shared_zone', app_name='shared_zone')),
    # the request urls
    url(r'^request/', include('request.urls', namespace='request', app_name='request')),

    # the request urls
    url(r'^statistics/', include('share_statistics.urls', namespace='share_statics', app_name='share_statistics')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

implementation/tool_sharing/user/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^sign_up/$', views.sig_up, name="sign_up"),
    url(r'^my_profile/$', views.my_profile, name="my_profile"),
    url(r'^update_profile/$', views.update_profile, name="update_profile"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^pickup_arrangement/$', views.pickup_arrangement, name="pickup_arrangement"),
    url(r'^promote_coordinator/$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^promote_coordinator/(?P<search_term>\w+)$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^history/$', views.history, name="history"),
    url(r'^forgot_password/$', views.forgot_password, name="forgot_password"),
]

implementation/tool_sharing/templates/tool_management/available_reviews.html
{% extends "base.html" %}

{% block head_title %}Available Reviews | {{ block.super }}{% endblock %}

{% block content %}

    {% if requests %}
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Available Reviews</h3>
          </div>
          <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-25">
                        <thead>
                            <tr>
                                <th>Tool</th>
                                <th>Owner</th>
                                <th>Request Date</th>
                                <th class="text-align-center">Link</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for request in requests %}
                            <tr>
                                <td>{{ request.tool.name }}</td>
                                <td>{{ request.lender }}</td>
                                <td>{{ request.date }}</td>
                                <td class="text-align-center"><a class="btn btn-primary btn-xs" href="{% url 'tool_listing:tool_detail' request.tool.id %}"><span class="glyphicon glyphicon-align-left" aria-hidden="true"></span> Leave Review</a></td>
                            </tr>
                        {% endfor %}
                        <tbody>
                    </table>
                </div>
            </div>
            <!-- Begin Paginator -->
            {% if requests.has_previous or requests.has_next %}
                <div class="panel-footer text-center">
                    <ul class="pagination light-pagination">
                        {% if requests.has_previous %}
                            <li><a href="?page={{ requests.previous_page_number }}">Prev</a></li>
                        {% endif %}

                        {% for page in requests.paginator.page_range %}
                            <li class="{% if requests.number == page %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}

                        {% if requests.has_next %}
                            <li><a href="?page={{ requests.next_page_number }}">Next</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
            <!-- End Paginator -->
        </div>
    {% endif %}
{% endblock %}

implementation/tool_sharing/templates/tool_management/details_tool.html
{% extends "base.html" %}
{# {% load crispy_forms_tags %} #}
{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}
{% block content %}
    <div class="row">
        {% if form %}
            <form method="POST" action="" enctype="multipart/form-data" class="detail-form">{% csrf_token %}
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ title }}</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-sm-6 col-sm-offset-3">
                            {% if not submitted %}
                                {% if update %}
                                    <input type="hidden" name="id" value="{{ pk }}">
                                {% endif %}
                                {# {{ form|crispy }} #}
                                {{ form.as_p }}
                                {% if img %}
                                    <a href="{{ img }}" target="_blank"><img width="136px" src="{{ img }}" alt="Tool"></a>
                                {% endif %}
                        {% endif %}
                    </div>
                    </div>
                    <div class="panel-footer">
                        <div class="text-center">
                            <p>
                                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> {{ bottom_title }}</button>
                                <a href="{% url "manage_tools:my_tools" %}" role="button" class="btn btn-default btn-large"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</a>
                            </p>
                        </div>
                    </div>
                </div>
            </form>
        {% else %}
            <div class="col-md-12">
                <h1 class="bs-callout-danger bs-callout">{{ not_found }}</h1>
            </div>
        {% endif %}
    </div>
    {% if success %}
        <button type="button" class="btn btn-primary msg-alert hide" data-toggle="modal" data-target=".bs-example-modal-sm">msg</button>
          <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-body">
                  <a class="close" href="{% url "manage_tools:my_tools" %}" aria-label="Close"><span aria-hidden="true">&times;</span></a>
                  {{ msg }}
                </div>
              </div>
            </div>
          </div>
      {% endif %}
{% endblock %}

implementation/tool_sharing/templates/tool_management/my_tools.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xm-12">
            <a class="btn btn-info float-right-bottom" href="{% url "manage_tools:new_tool" %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add New Tool</a>
        </div>
    </div>

    {% if tools %}
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">My Tools</h3>
          </div>
          <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Picture</th>
                                <th>Shared from</th>
                                <th>Category</th>
                                <th class="text-align-center">Update</th>
                                <th class="text-align-center">Delete</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for tool in tools %}
                            <tr>
                                <td>{{ tool.name|slice:":30" }}{% if tool.name|length|get_digit:"-1" > 30 %}...{% endif %}</td>
                                <td>{{ tool.description|slice:":40"}}{% if tool.description|length|get_digit:"-1" > 40 %}...{% endif %}</td>
                                <td><img src="{{ tool.picture.url }}" alt="{{ tool.name }}" width="42"></td>
                                <td>{{ tool.get_shared_choices }}</td>
                                <td>{{ tool.category.name }}</td>
                                {% if tool.status != tool.BORROWED %}
                                <td class="text-align-center"><a href="{% url "manage_tools:edit_tool" tool.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                                <td class="text-align-center"><a href="{% url "manage_tools:remove_tool" tool.id %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></td>
                                <td>
                                    <select class="form-control upd_status">
                                        {% for status in tool.editable_status_choices %}
                                            <option {% if status.0 == tool.status %} selected="selected" {% endif %}value="{{ status.0 }},{% url "manage_tools:update_status" tool.id %}">{{ status.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                {% else %}
                                    <td></td>
                                    <td></td>
                                    <td>{{ tool.get_status_choices }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        <tbody>
                    </table>
                </div>
            </div>
            <!-- Begin Paginator -->
            {% if tools.has_previous or tools.has_next %}
                <div class="panel-footer text-center">
                    <ul class="pagination light-pagination">
                        {% if tools.has_previous %}
                            <li><a href="?page={{ tools.previous_page_number }}">Prev</a></li>
                        {% endif %}

                        {% for page in tools.paginator.page_range %}
                            <li class="{% if tools.number == page %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        
                        {% if tools.has_next %}
                            <li><a href="?page={{ tools.next_page_number }}">Next</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
            <!-- End Paginator -->
        </div>
    {% endif %}
{% endblock %}

implementation/tool_sharing/templates/tool_management/tool_rate.html
{% extends "base.html" %}
{# {% load crispy_forms_tags %} #}
{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}
{% block content %}
    <form class="form-signin" method="POST" action="">
              <div    >

</div>
            {% csrf_token %}
            <h2 class="form-signin-heading text-align-center">{{title }}</h2>
        <strong>{{ msg}}</strong>
            <hr />
            {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
          </form>
{% endblock %}