implementation/tool_sharing/tool_sharing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from user.views import sign_in, log_out


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^sign_in/$', sign_in, name="sign_in"),
    url(r'^log_out/$', log_out, name="log_out"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^manage_tools/', include('manage_tools.urls', namespace="manage_tools", app_name='manage_tools')),
    url(r'^account/', include('user.urls', namespace='user', app_name='user')),
    # the tool listing urls
    url(r'^tools/', include('tool_listing.urls', namespace='tool_listing', app_name='tool_listing')),
    # shed creating
    url(r'^shared_zone/', include('shared_zone.urls', namespace='shared_zone', app_name='shared_zone')),
    # the request urls
    url(r'^request/', include('request.urls', namespace='request', app_name='request')),

    # the request urls
    url(r'^statistics/', include('share_statistics.urls', namespace='share_statics', app_name='share_statistics')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

implementation/tool_sharing/user/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^sign_up/$', views.sig_up, name="sign_up"),
    url(r'^my_profile/$', views.my_profile, name="my_profile"),
    url(r'^update_profile/$', views.update_profile, name="update_profile"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^pickup_arrangement/$', views.pickup_arrangement, name="pickup_arrangement"),
    url(r'^promote_coordinator/$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^promote_coordinator/(?P<search_term>\w+)$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^history/$', views.history, name="history"),
    url(r'^forgot_password/$', views.forgot_password, name="forgot_password"),
]

implementation/tool_sharing/user/models.py
from django.db import models
from utils.utilities import USStates
from shared_zone.models import SharedZone
from tool_sharing.settings import ADMIN_CODE


class Role(models.Model):

    ADMIN = "ADMIN"
    USER = "USER"
    role_choices = (
        (ADMIN, "Administrator"),
        (USER, "Regular user"),
    )

    code = models.CharField(max_length=5, unique=True)
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    def get_role_choices(self, code):
        return dict(self.role_choices).get(code)

    def post_roles(self):
        try:
            role = Role()
            role.code = self.ADMIN
            role.name = self.get_role_choices(self.ADMIN)
            role.description = "Shared Zone coordinator."
            role.save()
        except:
            pass

        try:
            role = Role()
            role.code = self.USER
            role.name = self.get_role_choices(self.USER)
            role.description = "Shared Zone user."
            role.save()
        except:
            pass


class User(models.Model):
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=20)
    password = models.CharField(max_length=100)
    address = models.CharField(max_length=50)
    state = models.CharField(max_length=50, choices=USStates.states_list)
    city = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=5)
    shared_zone = models.ForeignKey(SharedZone, related_name='users', null=True, on_delete=models.SET_NULL)
    role = models.ForeignKey(Role, related_name='users', null=True, on_delete=models.SET_NULL)
    role_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    enabled = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    pickup_days = models.CharField(max_length=100, null=True)
    pickup_times = models.CharField(max_length=50, null=True)

    def is_admin(self):
        return self.role.code == ADMIN_CODE

    def get_address(self):
        return self.address + ". " + self.city + ", " + self.state

    def __str__(self):
        return self.last_name + ", " + self.first_name + " " + self.middle_name

implementation/tool_sharing/user/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .forms import RegistrationForm, LogInForm, UpdateProfileForm, UpdatePasswordForm, PickupArrangementForm, ForgotPasswordForm
from utils import utilities
from user.models import User, Role
from shared_zone.models import SharedZone
from request.models import Notification
from django.http import HttpResponseForbidden
from django.contrib import messages
import datetime
from django.db.models import Q  # for making queries
from tool_sharing.settings import ADMIN_CODE
from request.models import Request
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import string
import random
from manage_tools.models import Tool
from tool_sharing.settings import DEFAULT_FROM_EMAIL


def sig_up(request):
    if utilities.is_user_logged_in(session=request.session):
        return redirect(reverse('index'))
    title = "Sign Up"
    button_title = "Sign Up"
    form = RegistrationForm(request.POST or None)
    context = {
        "title": title,
        "form": form,
        "button_title": button_title
    }
    if request.method == 'POST':
        if form.is_valid():
            user = form.save(commit=False)
            user.password = utilities.hash_password(user.password)
            is_shared_zone = SharedZone.objects.filter(zipcode=user.zipcode, enabled=1).exists()
            try:
                role = Role.objects.get(code=Role.USER)
                user.role = role
            except Role.DoesNotExist:
                pass
            if is_shared_zone:
                user.shared_zone = SharedZone.objects.get(zipcode=user.zipcode)
                request.session['is_shared_zone'] = True
            user.save()
            notification = Notification(user=user)
            notification.save()

            try:
                utilities.send_email('registration.txt', 'registration.html', {'url': "http://localhost:8000", 'email': DEFAULT_FROM_EMAIL}, "Welcome to Tool Sharing", user.email)
            except Exception as e:
                print(e)

            request.session['cool_user'] = user.id
            request.session['cool_user_name'] = user.last_name + ", " + user.first_name
            if user.role is not None:
                request.session['user_role'] = user.role.code

            # Display the user a success message
            messages.success(request, 'Your account registered successfully')

            if not is_shared_zone:
                return redirect(reverse('shared_zone:index'))
            return redirect(reverse('index'))
    return render(request, "user/user_detail.html", context)


def sign_in(request):
    if request.method == 'GET':
        if utilities.is_user_logged_in(session=request.session):
            user = User.objects.get(id=request.session["cool_user"], enabled=1)
            if not SharedZone.objects.filter(zipcode=user.zipcode, enabled=1).exists():
                return redirect(reverse('shared_zone:index'))
            request.session['is_shared_zone'] = True
            return redirect(reverse('index'))
    title = "Sign In"
    form = LogInForm(request.POST or None)
    context = {
        "title": title,
        "form": form
    }
    if request.method == 'POST':
        if form.is_valid():

            user = User.objects.get(email=form.cleaned_data["email"], enabled=1)
            request.session['cool_user'] = user.id
            request.session['cool_user_name'] = user.last_name + ", " + user.first_name

            is_shared_zone = SharedZone.objects.filter(zipcode=user.zipcode, enabled=1).exists()
            if not is_shared_zone:
                return redirect(reverse('shared_zone:index'))
            if not user.shared_zone:
                user.shared_zone = SharedZone.objects.get(zipcode=user.zipcode, enabled=1)
                user.save()
            request.session['is_shared_zone'] = True

            # The promote coordinator session to control the menu item
            request.session['user_role'] = user.role.code

            try:
                notification = Notification.objects.get(user=user)
            except Notification.DoesNotExist:
                notification = Notification(user=user)
                notification.save()
            if notification.pending_received > 0:
                request.session['notification_r'] = notification.pending_received
            if notification.pending_sent > 0:
                request.session['notification_s'] = notification.pending_sent
            return redirect(reverse('index'))
    return render(request, "user/sing_in.html", context)


def log_out(request):
    try:
        del request.session['cool_user']
    except KeyError:
        pass
    try:
        del request.session['is_shared_zone']
    except KeyError:
        pass
    try:
        del request.session['cool_user_name']
    except KeyError:
        pass
    try:
        del request.session['user_role']
    except KeyError:
        pass
    try:
        del request.session['notification_s']
    except KeyError:
        pass
    try:
        del request.session['notification_r']
    except KeyError:
        pass
    return redirect(reverse('sign_in'))


def my_profile(request):
    if not utilities.is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    user = User.objects.get(id=request.session["cool_user"])
    return render(request, "user/my_profile.html", {"my_profile": True, "title": "Update Profile", "user": user})


def update_profile(request):
    if not utilities.is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if request.method == 'GET':
        user = User.objects.get(id=request.session["cool_user"])
        form = UpdateProfileForm(request.POST or None, instance=user)
    if request.method == 'POST':
        user = User.objects.get(id=request.session["cool_user"])
        old_zipcode = user.zipcode
        form = UpdateProfileForm(request.POST or None, instance=user)
        if form.is_valid():
            if user.zipcode != old_zipcode and Tool.objects.filter(owner=user, status=Tool.BORROWED, enabled=True).count() > 0:
                context = {
                    "title": "Update Profile",
                    "form": form,
                    "button_title": "Save",
                    "my_profile": True,
                    "update": True,
                    'error_message': "You cannot change your zipcode. You have borrowed tools."
                }
                return render(request, "user/user_detail.html", context)
            elif user.zipcode != old_zipcode and Tool.objects.filter(owner=user, shared_from=Tool.SHED, enabled=True).count() > 0:
                context = {
                    "title": "Update Profile",
                    "form": form,
                    "button_title": "Save",
                    "my_profile": True,
                    "update": True,
                    'error_message': "You cannot change your zipcode. You have tools in the Community Shed."
                }
                return render(request, "user/user_detail.html", context)
            elif user.is_admin() and user.zipcode != old_zipcode and User.objects.filter(zipcode=user.zipcode, role=user.role).exclude(pk=user.id).count() == 0:
                context = {
                    "title": "Update Profile",
                    "form": form,
                    "button_title": "Save",
                    "my_profile": True,
                    "update": True,
                    'error_message': "You are the only Administrator is this Shared Zone. Please promote someone else to Administrator before changing your zipcode."
                }
                return render(request, "user/user_detail.html", context)
            user = form.save(commit=False)
            request.session['cool_user_name'] = user.last_name + ", " + user.first_name
            if SharedZone.objects.filter(zipcode=user.zipcode, enabled=1).exists():
                user.shared_zone = SharedZone.objects.get(zipcode=user.zipcode, enabled=1)
                user.role = Role.objects.get(code="USER")
                user.save()
            else:
                user.shared_zone = None
                user.save()
                return redirect(reverse('shared_zone:index'))
            messages.success(request, 'Your profile was updated successfully.')
            return redirect(reverse('user:my_profile'))
    context = {
        "title": "Update Profile",
        "form": form,
        "button_title": "Save",
        "my_profile": True,
        "update": True
    }
    return render(request, "user/user_detail.html", context)


# here is the code for changing the password
def change_password(request):
    if not utilities.is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    title = "Change Password"
    form = UpdatePasswordForm(request.POST or None)
    success = None

    if request.method == 'POST':
        user = User.objects.get(id=request.session["cool_user"], enabled=1)
        form.set_current_password(user.password)
        if form.is_valid():
            user.password = utilities.hash_password(form.cleaned_data["new_password"])  # change password to hash
            user.save()
            success = True
    context = {
        "title": title,
        "my_profile": True,
        "form": form,
        "success": success
    }

    return render(request, "user/change_password.html", context)


def pickup_arrangement(request):
    if not utilities.is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))

    user = User.objects.get(id=request.session["cool_user"], enabled=1)
    form = PickupArrangementForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            pickup_days = ' '.join(request.POST.getlist('days'))

implementation/tool_sharing/templates/user/change_password.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

    {% block content %}
      <form class="form-signin" method="POST" action="">
        {% csrf_token %}
        <h2 class="form-signin-heading text-align-center">{{title}}</h2>
        <hr />
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Update</button>
      </form>

      {% if success %}
        <button type="button" class="btn btn-primary msg-alert hide" data-toggle="modal" data-target=".bs-example-modal-sm">msg</button>
          <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-body">
                  <a class="close" href="{% url "user:my_profile" %}" aria-label="Close"><span aria-hidden="true">&times;</span></a>
                  Password changed successfully
                </div>
              </div>
            </div>
          </div>
      {% endif %}
    {% endblock %}

implementation/tool_sharing/templates/user/forgot_password.html
{% extends "base.html" %}

{% block head_title %}Forgot Password | {{ block.super }}{% endblock %}

    {% block content %}
          <form class="form-signin" method="POST" action="">
            {% csrf_token %}
            <h2 class="form-signin-heading text-align-center">Forgot Password</h2>
            <hr />
            {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" type="submit"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Reset Password</button>
          </form>
        {% if message %}
            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="alert alert-warning" style="margin-top: 10px;" role="alert">{{ message }}</div>
                </div>
            </div>
        {% endif %}
    {% endblock %}

implementation/tool_sharing/templates/user/history.html
{% extends "base.html" %}

{% block head_title %}Borrowing History | {{ block.super }}{% endblock %}

{% block content %}

    {% if history %}
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Borrowing History</h3>
          </div>
          <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th style="width:16%">Tool</th>
                                <th style="width:14%">Owner</th>
                                <th style="width:14%">Borrower</th>
                                <th style="width:10%">Request Date</th>
                                <th style="width:10%">Return Date</th>
                                <th style="width:10%">Status</th>
                                <th style="width:16%">Comment</th>
                                <th style="width:10%">Shared From</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for record in history %}
                            <tr>
                                <td>{{ record.tool.name }}</td>
                                <td>{{ record.lender }}</td>
                                <td>{{ record.borrower }}</td>
                                <td>{{ record.date }}</td>
                                <td>{% if record.returned_date %}{{ record.returned_date }}{% endif %}</td>
                                <td>{{ record.get_status_choices }}</td>
                                <td>{{ record.comment }}</td>
                                <td>{{ record.tool.get_shared_choices }}</td>
                            </tr>
                        {% endfor %}
                        <tbody>
                    </table>
                </div>
            </div>
            <!-- Begin Paginator -->
            {% if history.has_previous or history.has_next %}
                <div class="panel-footer text-center">
                    <ul class="pagination light-pagination">
                        {% if sent_requests.has_previous %}
                            <li><a href="?page={{ history.previous_page_number }}">Prev</a></li>
                        {% endif %}

                        {% for page in history.paginator.page_range %}
                            <li class="{% if history.number == page %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}

                        {% if history.has_next %}
                            <li><a href="?page={{ history.next_page_number }}">Next</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
            <!-- End Paginator -->
        </div>
    {% endif %}
{% endblock %}

implementation/tool_sharing/templates/user/my_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}
{% block content %}
    <div class="row">
      {% if messages %}
        {% for msg in messages %}       
          <div class="alert alert-{{msg.level_tag}}" style="margin-bottom: 10px;" role="alert">{{msg.message}}</div>
        {% endfor %}
      {% endif %}
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">My Profile</h3>
        </div>
        <div class="panel-body">
          
            <div class="row">
                  <!-- small centered image -->
                  <div class="col-md-2 col-lg-offset-2">
                    <div>
                      <a href="#" class="thumbnail">
                        <img src="{% static "img/avatar_profile.png" %}" alt="User photo">
                      </a>
                    </div>
                  </div>
                  <!-- small centered image -->
                <!-- the user information -->
                <div class="col-sm-8">
                    <div class="col-md-12">
                        <div class="jumbotron" style="background: transparent;padding: 0 10px;">
                          <h2>{{ user.first_name | title}} {{ user.middle_name | title }} {{ user.last_name | title}}</h2>
                            </br>
                          <h4>Email:</h4>
                          <h3 style="margin-left: 30px;">{{ user.email }}</h3>
                          <h4>Phone number:</h4>
                          <h3 style="margin-left: 30px;">{{ user.phone_number }}</h3>
                          <h4>Address:</h4>
                          <h3 style="margin-left: 30px;">{{ user.address }}</h3>
                          <h3 style="margin-left: 30px;">{{ user.city }}, {{ user.state }} {{ user.zipcode }}</h3>
                        </div>
                    </div>
                </div>
                <!-- /the user information -->
            </div>
        </div>
        <div class="panel-footer">
            <div class="text-center">
                  <a href="{% url "user:update_profile" %}" class="btn btn-primary" role="button"><span aria-hidden="true"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Update</span></a>
            </div>
        </div>
    </div>
{% endblock %}

implementation/tool_sharing/templates/user/pickup_arrangement.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
  <style type="text/css">
    .errors {
      color:red;
      font-weight:bold;
    }
  </style>
  <form action="#" method="POST" role="form">
    {% csrf_token %}  
     <div class="row">
        <legend>Pickup arrangement</legend>
        <div class="col-md-2">
          {% for day in form.week_days %}
            <div class="checkbox">
                <label>
                  <input type="checkbox" name="days" value="{{day}}" {% if day in pickup_days %} checked {% endif %}>
                  {{day}}
                </label>
              </div>
          {% endfor %}

          <span class="errors">{{form.errors.days.0}}</span>
        </div>

        <div class="col-md-8">
          <label>From
            <input type="time" name="time_from" id="time_from" class="form-control"  value="{{pickup_times.0}}" required="true" title="">
          </label>
          <span class="errors">{{form.errors.time_from.0}}</span>
          {{form.fi}}
          <label style="margin-left: 20px;">To
            <input type="time" name="time_to" id="time_to" class="form-control" value="{{pickup_times.1}}"  title="">
          </label>
          <span class="errors">{{form.errors.time_to.0}}</span>
        </div>
     </div>
    
    <button type="submit" class="btn btn-primary" style="margin-top:50px;">Set time</button>
  </form>

  {% if form.non_field_errors %}
    <div class="alert alert-danger" style="margin-top:30px;"> 
      {{ form.non_field_errors }}
    </div>
  {% endif %}

  {% if messages %}
    <div class="alert alert-success" style="margin-top:30px;">
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    </div>
  {% endif %}


{% endblock %}
    

implementation/tool_sharing/templates/user/promote_coordinator.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}

<h1 class="page-header">Manage Coordinators</h1>
  <nav class="navbar navbar-default">
    <div class="row">
    <div class="col-sm-6 col-sm-offset-3" style="margin-top: .6%;margin-bottom: .6%;">
        <div class="input-group">
          <input type="text" id="search_term" class="form-control" placeholder="Firstname or email" value="{{ search_term }}">
          <span class="input-group-btn">
            <button type="button" class="btn btn-default" aria-label="Left Align" onclick="doSearch()">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
          </span>
        </div>
      </div>
  </div>
  </nav>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
        {% if messages %}
          {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}}" style="margin-bottom: 10px;" role="alert">{{msg.message}}</div>
          {% endfor %}
        {% endif %}
        </div>
    </div>
  <div class="row">
      <div class="col-sm-6">
        {% if users_in_zone %}
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Username</th>
                <th>Email</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for user in users_in_zone %}
                <tr>
                  <td>{{forloop.counter}}</td>
                  <td>{{ user.last_name }}, {{ user.first_name }} {{ user.middle_name }} </td>
                  <td>{{ user.email }}</td>
                  <td>
                    <form action="" method="POST" role="form">
                      {% csrf_token %}
                      <input type="hidden" name="user_id" value="{{user.id}}">                                
                      <button type="submit" class="btn btn-primary">Promote</button>
                    </form>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
            {% else %}
            <div class="alert alert-info">
              The user does not exist.
            </div>
            {% endif %}
      </div>
      <div class="col-sm-6">
          {% if admins_in_zone %}
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for admin_in_zone in admins_in_zone %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{ admin_in_zone.last_name }}, {{ admin_in_zone.first_name }} {{ admin_in_zone.middle_name }}</td>
                      <td>{{ admin_in_zone.email }}</td>
                      <td>
                        <form action="" method="POST" role="form">
                          {% csrf_token %}
                          <input type="hidden" name="user_id" value="{{admin_in_zone.id}}">                                
                          <input type="hidden" name="cancel_admin_operation" value="true">                                
                          <button type="submit" class="btn btn-danger">Remove</button>
                        </form>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
          {% else %}
            <div class="alert alert-info">
              The user does not exist.
            </div>
          {% endif %}
        </div>
    </div>
    <script type="text/javascript">
      function doSearch(){
        var search_term = $('#search_term').val();
        var url = '{% url "user:promote_coordinator" %}' + search_term;
        window.location = url
      }
    </script>
{% endblock %}

implementation/tool_sharing/templates/user/sing_in.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

    {% block content %}
          <form class="form-signin" method="POST" action="">
            {% csrf_token %}
            <h2 class="form-signin-heading text-align-center">Welcome</h2>
            <hr />
            {{ form.as_p }}
            <button class="btn btn-lg btn-primary btn-block" type="submit"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Sign in</button>
          </form>
      <p class="text-align-center"><a href="{% url "user:sign_up" %}">Sign Up</a> | <a href="{% url "user:forgot_password" %}">Forgot Password</a></p>
    {% endblock %}

implementation/tool_sharing/templates/user/user_detail.html
{% extends "base.html" %}
{# {% load crispy_forms_tags %} #}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
        <form method="POST" action="" class="form form-horizontal" role="form">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
              </div>
              <div class="panel-body">
                  <div class="col-sm-6 col-sm-offset-3">
                    {% csrf_token %}
                    {{ form.as_p }}
                  </div>
                  {% if error_message %}
                  <div class="row">
                      <div class="col-sm-10 col-sm-offset-1 alert alert-danger"><strong>{{ error_message }}</strong></div>
                  </div>
                  {% endif %}
              </div>
              <div class="panel-footer">
                <div class="text-center">
                  <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> {{ button_title }}</button>
                      {% if update %}
                          <a href="{% url "user:my_profile" %}" class="btn btn-default btn-large" role="button"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</a>
                      {% endif %}
                </div>  
              </div>
            </div>
        </form>
{% endblock %}