implementation/tool_sharing/manage_tools/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^review_review/(?P<pk>[0-9]+)/$', views.review_review, name="review_review"),
    url(r'^my_tools/$', views.my_tools, name="my_tools"),
    url(r'^new_tool/$', views.new_tool, name="new_tool"),
    url(r'^get_reviews/(?P<pk>[0-9]+)/$', views.get_reviews, name="get_reviews"),
    url(r'^post_review/(?P<pk>[0-9]+)/$', views.post_review, name="post_review"),
    url(r'^edit_tool/(?P<pk>[0-9]+)/$', views.edit_tool, name="edit_tool"),
    url(r'^remove_tool/(?P<pk>[0-9]+)/$', views.remove_tool, name="remove_tool"),
    url(r'^update_status/(?P<pk>[0-9]+)/$', views.update_status, name="update_status"),
    url(r'^available_reviews/$', views.available_reviews, name="available_reviews"),
]

implementation/tool_sharing/request/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^sent/$', views.sent, name="sent"),
    url(r'^received/$', views.received, name="received"),
    url(r'^action/$', views.action, name="action"),
    url(r'^return_tool/(?P<pk>[0-9]+)/$', views.return_tool, name="return_tool"),
    url(r'^move_to_history/(?P<ac>[a-z]+)/(?P<pk>[0-9]+)/$', views.move_to_history, name="move_to_history"),
]

implementation/tool_sharing/share_statistics/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^community/$', views.community_statistics, name="community_statistics"),
    url(r'^individual/$', views.individual_statistics, name="individual_statistics"),
]

implementation/tool_sharing/shared_zone/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/$', views.update_sharedzone, name='update'),
]

implementation/tool_sharing/tool_sharing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from user.views import sign_in, log_out


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^sign_in/$', sign_in, name="sign_in"),
    url(r'^log_out/$', log_out, name="log_out"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^manage_tools/', include('manage_tools.urls', namespace="manage_tools", app_name='manage_tools')),
    url(r'^account/', include('user.urls', namespace='user', app_name='user')),
    # the tool listing urls
    url(r'^tools/', include('tool_listing.urls', namespace='tool_listing', app_name='tool_listing')),
    # shed creating
    url(r'^shared_zone/', include('shared_zone.urls', namespace='shared_zone', app_name='shared_zone')),
    # the request urls
    url(r'^request/', include('request.urls', namespace='request', app_name='request')),

    # the request urls
    url(r'^statistics/', include('share_statistics.urls', namespace='share_statics', app_name='share_statistics')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

implementation/tool_sharing/user/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^sign_up/$', views.sig_up, name="sign_up"),
    url(r'^my_profile/$', views.my_profile, name="my_profile"),
    url(r'^update_profile/$', views.update_profile, name="update_profile"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^pickup_arrangement/$', views.pickup_arrangement, name="pickup_arrangement"),
    url(r'^promote_coordinator/$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^promote_coordinator/(?P<search_term>\w+)$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^history/$', views.history, name="history"),
    url(r'^forgot_password/$', views.forgot_password, name="forgot_password"),
]

implementation/tool_sharing/request/models.py
from django.db import models
from manage_tools.models import Tool
from user.models import User


class Request(models.Model):
    PENDING_APPROVAL = 'PA'
    APPROVED = 'AP'
    REJECTED = 'RE'
    RETURNED = 'RT'

    status_choices = (
        (PENDING_APPROVAL, 'Pending Approval'),
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
        (RETURNED, 'Returned')
    )

    tool = models.ForeignKey(Tool, related_name='requests')
    lender = models.ForeignKey(User, related_name='lender_requests')
    borrower = models.ForeignKey(User, related_name='borrower_requests')
    status = models.CharField(choices=status_choices, max_length=2, default="PA")
    comment = models.CharField(max_length=150, default="")
    date = models.DateTimeField(auto_now_add=True, auto_now=False)
    returned_date = models.DateTimeField(null=True)
    shared_from = models.CharField(choices=Tool.shared_choices, max_length=2)
    zipcode = models.CharField(max_length=5)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    borrower_enabled = models.BooleanField(default=True)
    lender_enabled = models.BooleanField(default=True)
    may_leave_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.status + " - " + str(self.tool.id) + " - " + str(self.lender.id) + " - " + str(self.borrower.id)

    def get_status_choices(self):
        return dict(self.status_choices).get(self.status)


class Notification(models.Model):
    user = models.OneToOneField(User)
    pending_sent = models.PositiveSmallIntegerField(default=0)
    pending_received = models.PositiveSmallIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.user.last_name + ", " + self.user.first_name

    def increment_sent(self):
        self.pending_sent += 1

    def increment_received(self):
        self.pending_received += 1

implementation/tool_sharing/request/views.py
from django.shortcuts import render
from utils.utilities import is_user_logged_in, send_email
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponseForbidden
from .models import Request, Notification
from django.views.decorators.csrf import csrf_exempt
from user.models import User
from manage_tools.models import Tool
from django.contrib import messages
import datetime


def sent(request):
    if not is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if 'is_shared_zone' not in request.session:
        return redirect(reverse('shared_zone:index'))

    try:
        del request.session['notification_s']
        notification = Notification.objects.get(user=request.session["cool_user"])
        notification.pending_sent = 0
        notification.save()
    except KeyError:
        pass
    sent_requests = Request.objects.filter(borrower=request.session["cool_user"], borrower_enabled=True).order_by('-id')

    paginator = Paginator(sent_requests, 10)
    page = request.GET.get('page')
    try:
        sent_requests = paginator.page(page)
    except PageNotAnInteger:
        sent_requests = paginator.page(1)
    except EmptyPage:
        sent_requests = paginator.page(paginator.num_pages)

    context = {
        'sent_requests': sent_requests,
        'my_requests': True
    }
    return render(request, "request/sent_requests.html", context)


def received(request):
    if not is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if 'is_shared_zone' not in request.session:
        return redirect(reverse('shared_zone:index'))
    try:
        del request.session['notification_r']
        try:
            notification = Notification.objects.get(user=request.session["cool_user"])
            notification.pending_received = 0
            notification.save()
        except Notification.DoesNotExist:
            notification = Notification(user=request.session["cool_user"])
            notification.save()
    except KeyError:
        pass
    user = User.objects.get(pk=request.session["cool_user"])
    if user.role.code == user.role.USER:
        received_requests = Request.objects.filter(lender=request.session["cool_user"], shared_from=Tool.HOME, lender_enabled=True).order_by('-id')
    elif user.role.code == user.role.ADMIN:
        received_requests = Request.objects.filter(lender=request.session["cool_user"], lender_enabled=True).order_by('-id')
    paginator = Paginator(received_requests, 10)
    page = request.GET.get('page')
    try:
        received_requests = paginator.page(page)
    except PageNotAnInteger:
        received_requests = paginator.page(1)
    except EmptyPage:
        received_requests = paginator.page(paginator.num_pages)

    context = {
        'received_requests': received_requests,
        'my_requests': True
    }
    return render(request, "request/received_requests.html", context)


@csrf_exempt
def action(request):
    if not is_user_logged_in(session=request.session):
        return JsonResponse({'status_code': 500, 'message': 'An error happened when approving or rejecting the request'})
    if 'is_shared_zone' not in request.session:
        return JsonResponse({'status_code': 500, 'message': 'An error happened when approving or rejecting the request'})

    if request.method == 'POST':
        try:
            received_request = Request.objects.get(pk=request.POST['request_id'])
            if request.POST['action'] == Request.APPROVED and received_request.tool.status == received_request.tool.BORROWED:
                return JsonResponse({'status_code': 500, 'message': 'You cannot approve this request. The tool is borrowed.'})
            received_request.status = request.POST['action']
            received_request.comment = request.POST['comment']
            message = ""
            optional = ""

            if request.POST['action'] == Request.REJECTED:
                message = "The borrowing request was rejected successfully!"
            elif request.POST['action'] == Request.APPROVED:
                received_request.tool.status = received_request.tool.BORROWED
                received_request.tool.save()
                message = "The borrowing request was approved successfully!"
                optional = "Please return the tool as soon as you finish using it. Remind the owner to mark the tool as returned."
            received_request.save()
            try:
                notification = Notification.objects.get(user=received_request.borrower)
            except Notification.DoesNotExist:
                notification = Notification(user=received_request.borrower)
                notification.save()
            notification.increment_sent()
            notification.save()
            try:
                send_email('request_action.txt', 'request_action.html', {'tool_name': received_request.tool.name, 'request_status': received_request.get_status_choices(), 'message': received_request.comment, 'optional': optional}, "Borrowing Request Information", received_request.borrower.email)
            except Exception as e:
                print(e)
            response = {'statusCode': 200, 'message': message, 'status': received_request.get_status_choices()}
        except Exception as e:
            print(e)
            response = {'status_code': 500, 'message': 'An error happened when approving or rejecting the request'}
        return JsonResponse(response)


def return_tool(request, pk):
    if not is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if 'is_shared_zone' not in request.session:
        return redirect(reverse('shared_zone:index'))
    if request.method == 'GET':
        try:
            received_request = Request.objects.get(pk=pk)
        except Request.DoesNotExist:
            messages.error(request, "No such request exists. Please verify information.")
            return redirect(reverse('request:received'))
        user = User.objects.get(pk=request.session["cool_user"])
        if received_request.status == Request.APPROVED and ((received_request.shared_from == Tool.HOME and received_request.lender == user) or (received_request.shared_from == Tool.SHED and User.objects.filter(pk=user.id, role__code=user.role.ADMIN).count() == 1)):
            received_request.tool.status = Tool.AVAILABLE
            received_request.tool.save()
            received_request.status = Request.RETURNED
            received_request.may_leave_comment = True
            received_request.returned_date = datetime.datetime.now()
            received_request.save()
            messages.success(request, "The tool was marked as returned successfully.")
        else:
            messages.error(request, "Conditions to return the tool were not met.")
    return redirect(reverse('request:received'))


def move_to_history(request, ac, pk):
    if not is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if 'is_shared_zone' not in request.session:
        return redirect(reverse('shared_zone:index'))
    if request.method == 'GET':
        try:
            borrowing_request = Request.objects.get(pk=pk)
        except Request.DoesNotExist:
            return HttpResponseForbidden()
        if ac == "sent" and borrowing_request.borrower.id == request.session["cool_user"]:
            borrowing_request.borrower_enabled = False
            borrowing_request.save()
            return redirect(reverse('request:sent'))
        elif ac == "received" and borrowing_request.lender.id == request.session["cool_user"]:
            borrowing_request.lender_enabled = False
            borrowing_request.save()
            return redirect(reverse('request:received'))
    return HttpResponseForbidden()

implementation/tool_sharing/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/x-mates.ico" %}">

    <title>{% block head_title %}Tool Sharing{% endblock %}</title>

    {% include "head_css.html" %}

    <style>
    {% block style %}

    {% endblock %}
    </style>
  </head>

  <body class="min-body-height">

    {% include "navbar.html" %}

    <div class="container" style="padding-top:0;">
        {% block jumbotron %}

        {% endblock %}

        {% block content %}

        {% endblock %}

    </div> <!-- /container -->

    <footer class="footer">
      <div class="container">
        <p class="text-muted text-align-center">Created by X-Mates Team &copy; 2015 | Copyright All Rights Reserved</p>
      </div>
    </footer>

    {% include "javascript.html" %}

  </body>
</html>

implementation/tool_sharing/templates/borrowing_request.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <body style="width:90%;margin:0 auto;">
        <div style="text-align: justify;text-justify: inter-word;border-radius: 6px;background-color: #eee;padding-right: 20px;padding-left: 20px;padding-top: 40px;padding-bottom: 40px;margin-top:40px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;line-height: 1.42857143;margin-bottom: 15px;font-size: 21px;font-weight: 200;">
            <img src="http://i.imgsafe.org/943de01.png" />
            <p>Thank you for using Tool Sharing!</p>

            <p><strong>{{ borrower }}</strong> has requested to borrow your <strong>{{ tool }}</strong>.</p>

            <p>Please login into the application to either approve or reject this request.</p>

            <p>Sincerely,<br/>X-Mates Team</p>
        </div>
    </body>
</html>

implementation/tool_sharing/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <body style="width:90%;margin:0 auto;">
        <div style="text-align: justify;text-justify: inter-word;border-radius: 6px;background-color: #eee;padding-right: 20px;padding-left: 20px;padding-top: 40px;padding-bottom: 40px;margin-top:40px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;line-height: 1.42857143;margin-bottom: 15px;font-size: 21px;font-weight: 200;">
            <img src="http://i.imgsafe.org/943de01.png" />
            <p>Thank you for using Tool Sharing! Please, login to the application using the following password.</p>

            <h2 style="text-align:center;">{{ password }}</h2>

            <p>Then change the password from the top menu. You will find this option under the "My Account" menu.</p>

            <p>Sincerely,<br/>X-Mates Team</p>
        </div>
    </body>
</html>

implementation/tool_sharing/templates/head_css.html
{% load staticfiles %}
<!-- Bootstrap core CSS -->
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static "css/navbar-static-top.css" %}" rel="stylesheet">
<link href="{% static "css/custom.css" %}" rel="stylesheet">
<link href="{% static "css/sticky-footer-navbar.css" %}" rel="stylesheet">
<link href="{% static "css/signin.css" %}" rel="stylesheet">

implementation/tool_sharing/templates/home.html
    {% extends "base.html" %}
    {% load staticfiles %}
    {% block head_title %}{{ title }} | {{ block.super }}{% endblock %}
    
    {% block jumbotron %}
        <div class="row">
            {% if messages %}
              {% for msg in messages %}       
                <div class="alert alert-{{msg.level_tag}}" style="margin-bottom: 10px;" role="alert">{{msg.message}}</div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="jumbotron">
            <div class="row">
                <div class="col-sm-12">
                    <h1 style="background: url('{% static "img/x-mates.ico" %}') no-repeat left"><span style="padding-left: 65px;">-Mates Team</span></h1>
                    <p>The Tool Sharing project is designed to make sharing tools among the community members easy. The goal is to help you lend and borrow tools from the comfort of your home.{% if "cool_user_name" not in request.session %} Join Us today!</p>
                    <p>
                      <a class="btn btn-lg btn-primary" href="{% url "user:sign_up" %}" role="button">Join Us &raquo;</a>
                    </p>
                    {% else %}
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endblock %}

    {% block content %}
        <div class="row">
            <div class="col-sm-4">
                <p class="lead text-align-center">Built with Django &amp; Bootstrap</p>
            </div>
            <div class="col-sm-4">
                <p class="lead text-align-center">Created by awesome developers</p>
            </div>
            <div class="col-sm-4">
                <p class="lead text-align-center">Always available</p>
            </div>
        </div>
    {% endblock %}

implementation/tool_sharing/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static "js/jquery-1.11.3.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}" ></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
<script src="{% static "js/angular.min.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>

implementation/tool_sharing/templates/navbar.html
    <!-- Static navbar -->
    {% load staticfiles %}
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url "index" %}" class="navbar-brand"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Tool Sharing</a></li>
              {% if "cool_user" in request.session and "is_shared_zone" in request.session %}
                <li class="{% if borrow %}active{% endif %}"><a href="{% url "tool_listing:tool_listing" %}"><span class="glyphicon glyphicon-transfer" aria-hidden="true"></span> Borrow</a></li>
                <li {% if my_tools %}class="active"{% endif %}><a href="{% url "manage_tools:my_tools" %}"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> My Tools</a></li>
                <li class="dropdown {% if my_requests %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-send" aria-hidden="true"></span> My Requests
                        <span class="badge">
                            {% if request.session.notification_s and request.session.notification_r %}
                                {{ request.session.notification_s|add:request.session.notification_r }}
                            {% elif request.session.notification_s %}
                                {{ request.session.notification_s }}
                            {% elif request.session.notification_r %}
                                {{ request.session.notification_r }}
                            {% else %} 0
                            {% endif %}
                        </span>
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url "request:sent" %}">Sent Requests <span class="badge">{% if request.session.notification_s %}{{ request.session.notification_s }}{% else %}0{% endif %}</span></a></li>
                      <li><a href="{% url "request:received" %}">Received Requests <span class="badge">{% if request.session.notification_r %}{{ request.session.notification_r }}{% else %}0{% endif %}</span></a></li>
                      <li><a href="{% url "manage_tools:available_reviews" %}">Available Reviews</a></li>
                    </ul>
                </li>
              {% endif %}
              {% if "cool_user" in request.session and "is_shared_zone" in request.session and "user_role" in request.session and request.session.user_role == 'ADMIN' %}
                  <li class="dropdown {% if manage_shared_zone %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Shared Zone<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url "share_statistics:community_statistics" %}">Community Statistics</a></li>
                        <li><a href="{% url "user:promote_coordinator" %}"></span> Manage Coordinators</a></li>
                        <li><a href="{% url "shared_zone:update" %}">Update Share Zone</a></li>
                    </ul>
                  </li>
              {% endif %}
              {% if "cool_user" in request.session %}
                  <li class="dropdown {% if my_profile %}active{% endif %}">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> My Account<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url "user:my_profile" %}">My Profile</a></li>
                      <li><a href="{% url "user:change_password" %}">Change Password</a></li>
                      <li><a href="{% url "user:pickup_arrangement" %}">Pickup Arrangement</a></li>
                        {% if 'is_shared_zone' in request.session %}
                            <li><a href="{% url "user:history" %}">Borrowing History</a></li>
                        {% endif %}
                    </ul>
                  </li>
              {% endif %}
          </ul>

        {% if not request.get_full_path == "/sign_in/" %}
          <ul class="nav navbar-nav navbar-right">
            {% if "cool_user_name" in request.session %}
                <li><a>[ Welcome {{ request.session.cool_user_name }} ]</a></li>
            {% endif %}
            {% if "cool_user" not in request.session %}
              <li><a href="{% url "sign_in" %}"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Sign In</a></li>
            {% endif %}
            {% if "cool_user" in request.session %}
              <li><a href="{% url "log_out" %}">Log Out <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
            {% endif %}
          </ul>
        {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

implementation/tool_sharing/templates/registration.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <body style="width:90%;margin:0 auto;">
        <div style="text-align: justify;text-justify: inter-word;border-radius: 6px;background-color: #eee;padding-right: 20px;padding-left: 20px;padding-top: 40px;padding-bottom: 40px;margin-top:40px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;line-height: 1.42857143;margin-bottom: 15px;font-size: 21px;font-weight: 200;">
            <img src="http://i.imgsafe.org/943de01.png" />
            <p>Thank you for joining Tool Sharing! You now have access to hundreds of thousands of tools and can interact with hundreds of people from your community.</p>

            <p>You can manage your account in the Tool Sharing online at {{ url }}.<br/>

            If you have any questions please email {{ email }}.</p>

            <p>Sincerely,<br/>X-Mates Team</p>
        </div>
    </body>
</html>

implementation/tool_sharing/templates/request_action.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <body style="width:90%;margin:0 auto;">
        <div style="text-align: justify;text-justify: inter-word;border-radius: 6px;background-color: #eee;padding-right: 20px;padding-left: 20px;padding-top: 40px;padding-bottom: 40px;margin-top:40px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;line-height: 1.42857143;margin-bottom: 15px;font-size: 21px;font-weight: 200;">
            <img src="http://i.imgsafe.org/943de01.png" />
            <p>Thank you for using Tool Sharing!</p>

            <p>Your borrowing request for a <strong>{{ tool_name }}</strong> has been <strong>{{ request_status }}</strong>.</p>

            <p>The following message was left regarding your request</p>

            <p><strong>{{ message }}</strong></p>

            <p>{{ optional }}</p>

            <p>Sincerely,<br/>X-Mates Team</p>
        </div>
    </body>
</html>