implementation/tool_sharing/manage_tools/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^review_review/(?P<pk>[0-9]+)/$', views.review_review, name="review_review"),
    url(r'^my_tools/$', views.my_tools, name="my_tools"),
    url(r'^new_tool/$', views.new_tool, name="new_tool"),
    url(r'^get_reviews/(?P<pk>[0-9]+)/$', views.get_reviews, name="get_reviews"),
    url(r'^post_review/(?P<pk>[0-9]+)/$', views.post_review, name="post_review"),
    url(r'^edit_tool/(?P<pk>[0-9]+)/$', views.edit_tool, name="edit_tool"),
    url(r'^remove_tool/(?P<pk>[0-9]+)/$', views.remove_tool, name="remove_tool"),
    url(r'^update_status/(?P<pk>[0-9]+)/$', views.update_status, name="update_status"),
    url(r'^available_reviews/$', views.available_reviews, name="available_reviews"),
]

implementation/tool_sharing/tool_listing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='tool_listing'),
    url(r'^(?P<id>[0-9]+)/$', views.tool_detail, name='tool_detail'),
]

implementation/tool_sharing/tool_sharing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from user.views import sign_in, log_out


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^sign_in/$', sign_in, name="sign_in"),
    url(r'^log_out/$', log_out, name="log_out"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^manage_tools/', include('manage_tools.urls', namespace="manage_tools", app_name='manage_tools')),
    url(r'^account/', include('user.urls', namespace='user', app_name='user')),
    # the tool listing urls
    url(r'^tools/', include('tool_listing.urls', namespace='tool_listing', app_name='tool_listing')),
    # shed creating
    url(r'^shared_zone/', include('shared_zone.urls', namespace='shared_zone', app_name='shared_zone')),
    # the request urls
    url(r'^request/', include('request.urls', namespace='request', app_name='request')),

    # the request urls
    url(r'^statistics/', include('share_statistics.urls', namespace='share_statics', app_name='share_statistics')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

implementation/tool_sharing/user/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^sign_up/$', views.sig_up, name="sign_up"),
    url(r'^my_profile/$', views.my_profile, name="my_profile"),
    url(r'^update_profile/$', views.update_profile, name="update_profile"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^pickup_arrangement/$', views.pickup_arrangement, name="pickup_arrangement"),
    url(r'^promote_coordinator/$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^promote_coordinator/(?P<search_term>\w+)$', views.promote_coordinator, name="promote_coordinator"),
    url(r'^history/$', views.history, name="history"),
    url(r'^forgot_password/$', views.forgot_password, name="forgot_password"),
]

implementation/tool_sharing/tool_listing/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from manage_tools.models import Tool, ToolCategory
from shared_zone.models import SharedZone
from user.models import User
from request.models import Request, Notification
# from faker import Faker
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q  # for making queries
from utils.utilities import is_user_logged_in, send_email
from django.http import JsonResponse
from django.core import serializers
from django.conf import settings

"""only available tools can be showed
   which determined as AV and enabled
   tools which is bit flag
"""


def index(request):
    if not is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if 'is_shared_zone' not in request.session:
        return redirect(reverse('shared_zone:index'))
    # prepare query params
    made_requests = Request.objects.filter(Q(borrower=request.session["cool_user"]), Q(status=Request.PENDING_APPROVAL) | Q(status=Request.APPROVED)).values('tool')
    user = User.objects.get(id=request.session["cool_user"], enabled=1)
    search_term = request.POST['search_term'] if request.POST else ''
    search_category = request.POST['search_category'] if request.POST else ''
    shared_from = request.POST['shared_from'] if request.POST else ''
    tools_list = Tool.objects.filter(
        Q(enabled=1),
        Q(status='AV'),
        Q(name__icontains=search_term) | Q(code__icontains=search_term),
        Q(category__in=ToolCategory.objects.filter(name__startswith=search_category).only(id)),
        Q(shared_from__startswith=shared_from),
        ~Q(owner=user.id),
        Q(owner__zipcode=user.zipcode),
        ~Q(id__in=made_requests)
    )
    paginator = Paginator(tools_list, 12)
    page = request.GET.get('page')
    try:
        tools = paginator.page(page)
    except PageNotAnInteger:
        tools = paginator.page(1)
    except EmptyPage:
        tools = paginator.page(paginator.num_pages)

    return render(request, 'tool_listing/index.html', {
        'tools': tools,
        'categories': category_list,
        'shared_from': Tool().get_all_shared_choices(),
        'borrow': True,
        'search_terms': request.POST,  # return user input
    })

"""The detail information of selected tool
"""


def tool_detail(request, id):
    if not is_user_logged_in(session=request.session):
        return redirect(reverse('sign_in'))
    if 'is_shared_zone' not in request.session:
        return redirect(reverse('shared_zone:index'))

    if request.method == 'GET':
        try:
            tool = Tool.objects.get(id=id, enabled=1)
            pickup_times = User.objects.filter(pk=tool.owner.id).values_list('pickup_days', 'pickup_times')
            pickup_times = list(pickup_times)[0]
            if pickup_times[0] is None or pickup_times[1] is None:
                pickup_times = None
            if tool.is_shared_from_home():
                pickup_address = tool.owner.get_address()
            else:
                pickup_address = SharedZone.objects.get(zipcode=tool.owner.zipcode).address
            may_leave_comment = False
            if Request.objects.filter(borrower=request.session["cool_user"], tool=id, status=Request.RETURNED, may_leave_comment=True).count() > 0:
                may_leave_comment = True
            context = {
                'pickup_address': pickup_address,
                'tool': tool,
                'borrow': True,
                'pickup_times': pickup_times,
                'id': id,
                'may_leave_comment': may_leave_comment
            }
            if "format" in request.GET and request.GET["format"] == "json":
                data = serializers.serialize("json", [tool])
                if pickup_times:
                    pu_times = {
                        'days': pickup_times[0],
                        'hours': pickup_times[1],
                    }
                else:
                    pu_times = None
                response = {'statusCode': 200, 'message': 'OK', 'data': data, 'media': settings.MEDIA_URL, 'pickup_times': pu_times, 'pickup_address': pickup_address}
                return JsonResponse(response)
        except Tool.DoesNotExist:
            context = {
                "not_found": 'The item you requested does not exist',
                'borrow': True,
                'id': id
            }
            if "format" in request.GET and request.GET["format"] == "json":
                response = {'statusCode': 404, 'message': 'The item you requested does not exist'}
                return JsonResponse(response)
        except Exception as e:
            print(e)
    if request.method == 'POST':
        try:
            tool = Tool.objects.get(pk=id, enabled=1)
            borrower = User.objects.get(pk=request.session["cool_user"], enabled=1)
            tool_request = Request(tool=tool, lender=tool.owner, borrower=borrower, zipcode=borrower.zipcode, shared_from=tool.shared_from)
            success_message = "The tool has been requested successfully! Please wait for owner's approval."
            if tool.shared_from == Tool.SHED:
                tool_request.comment = "Borrowing request approved!"
                success_message = "Borrowing request approved!"
                tool_request.status = Request.APPROVED
                tool.status = Tool.BORROWED
                tool.save()
                try:
                    request.session['notification_s'] += 1
                except KeyError:
                    request.session['notification_s'] = 1
                try:
                    optional = "Please return the tool as soon as you finish using it. Remind the shed coordinator to mark the tool as returned."
                    send_email('request_action.txt', 'request_action.html', {'tool_name': tool_request.tool.name, 'request_status': tool_request.get_status_choices(), 'message': tool_request.comment, 'optional': optional}, "Borrowing Request Information", tool_request.borrower.email)
                except Exception as e:
                    print(e)
            tool_request.save()
            if tool_request.tool.shared_from == Tool.HOME:
                try:
                    notification = Notification.objects.get(user=tool.owner)
                except Notification.DoesNotExist:
                    notification = Notification(user=tool.owner)
                    notification.save()
                notification.increment_received()
                notification.save()
                try:
                    send_email('borrowing_request.txt', 'borrowing_request.html', {'borrower': tool_request.borrower.__str__(), 'tool': tool_request.tool.name}, "Borrowing Request Information", tool_request.lender.email)
                except Exception as e:
                    print(e)
            context = {
                'tool': tool,
                'borrow': True,
                'message': success_message,
                'id': id
            }
            if "format" in request.POST and request.POST["format"] == "json":
                response = {'statusCode': 200, 'message': success_message}
                return JsonResponse(response)
        except Tool.DoesNotExist:
            context = {
                "not_found": 'The item you requested does not exist',
                'borrow': True,
                'id': id
            }
            if "format" in request.POST and request.POST["format"] == "json":
                response = {'statusCode': 404, 'message': 'The item you requested does not exist'}
                return JsonResponse(response)
        except Exception as e:
            print(e)
            context = {
                'tool': tool,
                'borrow': True,
                'id': id
            }
    return render(request, 'tool_listing/tool_detail.html', context)

def category_list():
    return ToolCategory.objects.order_by('name')

implementation/tool_sharing/templates/tool_listing/index.html
{% extends "base.html" %}

{% block content %}

    {% include "tool_listing/tool_detail_modal.html" %}

    <!-- The search bar of the tool listing thumbnails -->
    <div class="row">
        <nav class="navbar navbar-default">
            <div class="text-center">
                <form class="navbar-form" role="search" method="post" action="{% url 'tool_listing:tool_listing' %}">
                    <span class="label" style="color:black;">Shared from</span>
                    <select name="shared_from" class="form-control" placeholder="Shared from">
                        <option value="" selected="True">All</option>
                        {% for shared_from_location_key,shared_from_location_value in shared_from.items %}
                            <option value="{{ shared_from_location_key }}" {% if search_terms.shared_from == shared_from_location_key %} selected="True" {% endif %}>{{ shared_from_location_value }}</option>
                            
                        {% endfor %}
                    </select>

                    <span class="label" style="color:black;">Category</span>
                    <select name="search_category" class="form-control">
                        <option value="" selected="True">All</option>
                        {% for category in categories %}
                            <option value="{{ category.name }}" {% if search_terms.search_category == category.name %} selected="True" {% endif %}>{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <input name="search_term" type="text" class="form-control" placeholder="Search" value="{{ search_terms.search_term|default_if_none:'' }}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
        </nav>
    </div>
    <hr style="margin-top: 0;">
    <!-- /The search bar of the tool listing thumbnails -->


    <div class="row">
        <div class="jumbotron" style="background: transparent;padding-top:0;">
            {% load staticfiles %}
            <!-- The tools list thumbnail container-->
            <ul class="list-group">
                <div class="row">
                    {% for tool in tools %}
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail" style="border:0;min-height:500px;">
                                <a href="{% url 'tool_listing:tool_detail' id=tool.id %}" class="list_thumbnail_link" style="text-decoration: none;">
                                <img src="{{ tool.picture.url }}" alt="My image" style="height: 300px;" />
                                <div class="caption">
                                    <h3 style="font-weight: bolder;">{{ tool.name|title|slice:"0:20" }}</h3>
                                    <p style="font-weight: bolder;">{{ tool.description|slice:"0:40" }}...</p>
                                </div>
                                </a>
                                <button id="btn-{{ tool.id }}" data-toolid="{{ tool.id }}" class="btn btn-primary" data-toggle="modal" data-target="#toolDetailModal" data-url="{% url "tool_listing:tool_detail" tool.id %}"><span class="glyphicon glyphicon-send" aria-hidden="true"></span> Send request</button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </ul>
            <!-- /The tools list thumbnail container-->

            <!--paginator-->
            <div class="text-center">
                <ul class="pagination pagination-lg">
                    {% if tools.has_previous %}
                        <li><a href="?page={{ tools.previous_page_number }}">Prev</a></li>
                    {% endif %}
                    {% if tools.has_previous or tools.has_next %} <!-- tool not found - do not display paginator-->
                        {% for page in tools.paginator.page_range %}
                            <li class="{% if tools.number == page %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                    {% endif %}
                    {% if tools.has_next %}
                        <li><a href="?page={{ tools.next_page_number }}">Next</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/paginator-->
        </div>
    </div>
{% endblock %}

implementation/tool_sharing/templates/tool_listing/review.html
      <!-- /the tool information -->
      <span class="hide" id="url">{% url "manage_tools:get_reviews" pk=id %}</span>
      <div class="row" ng-app="toolReview">
        <div class="col-md-12" ng-controller="ToolController as toolCtr">
          <div class="tab">
          <!--  Tool Reviews List -->
            <ul>
              <h4 ng-show="toolCtr.reviews.length > 0">Reviews</h4>
              <li ng-repeat="review in toolCtr.reviews">
                <blockquote>
                  <strong>{$ review.fields.rate $} Stars</strong>
                  {$ review.fields.title $}
                  <br/>
                  {$ review.fields.description $}
                  <cite class="clearfix">&#8212; on {$ review.fields.timestamp | date $} by {$ review.fields.user_name $}</cite>
                </blockquote>
              </li>
            </ul>

            {% if may_leave_comment %}
            <form name="reviewForm" ng-controller="ReviewController as reviewCtrl" ng-submit="reviewForm.$valid && reviewCtrl.addReview('{% url "manage_tools:post_review" pk=id %}')" novalidate>{% csrf_token %}
              <blockquote ng-show="reviewCtrl.review">
                <b ng-show="reviewCtrl.review.rate">{$ reviewCtrl.review.rate $} Rate</b>
                <span ng-show="reviewCtrl.review.title">&#8212; {$ reviewCtrl.review.title $}</span>
                <br/>
                {$ reviewCtrl.review.description $}
                <br/>
                <cite class="clearfix"><b ng-show="reviewCtrl.review.user_name">By </b><span ng-show="reviewCtrl.review.user_name">{$ reviewCtrl.review.user_name $}</span></cite>
              </blockquote>
              <section ng-show="reviewCtrl.show">
                <h4>Submit a Review</h4>
                <select ng-model="reviewCtrl.review.rate" ng-options="rate for rate in [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]" class="form-control reposSortOrder topSpaceForm" required>
                  <option value="">Rate the Tool</option>
                </select>
                <input ng-model="reviewCtrl.review.title" class="form-control textField topSpaceForm" placeholder="Write a short title..." required />
                <textarea ng-model="reviewCtrl.review.description" placeholder="Write a short review of the tool..." class="form-control topSpaceForm resize-text-area-none" rows="3" required></textarea>
                <input ng-model="reviewCtrl.review.user_name" class="form-control textField topSpaceForm" placeholder="Leave user name here..." required />
                <p class="text-right"><a class="btn btn-danger topSpaceForm" href="{% url "manage_tools:review_review" id %}"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> Discard Review</a> <button type="submit" class="btn btn-primary topSpaceForm"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Submit Review</button></p>
              </section>
            </form>
            {% endif %}
          </div>
        </div>
      </div>

implementation/tool_sharing/templates/tool_listing/tool_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
  <div class="container-fluid">
  {% if message %}
      <div class="row" style="margin-bottom: 20px;">
          <div class="col-sm-12">
              <div class="alert alert-success" role="alert"><strong>{{ message }}</strong></div>
          </div>
      </div>
  {% endif %}
    <div class="row">
    {% if tool %}
    {% comment %}
      <!-- Small left images -->
      <div class="col-md-1">
        {% for count in '123' %}
          <div class="row">
              <a href="#" class="thumbnail">
                <img src="{% static "img/no-image.png" %}" alt="...">
              </a>
          </div>
        {% endfor %}
      </div>
      <!-- /Small left images -->
      {% endcomment %}

      <!-- Big centered image -->
      <div class="col-md-4">
        <div>
          <a href="{{ tool.picture.url }}" class="thumbnail" target="_blank">
            <img src="{{ tool.picture.url }}" alt="{{tool.name}}">
          </a>
        </div>
      </div>
      <!-- /Big centered image -->

      <!-- the tool information -->
      <div class="col-md-8">
        <div class="jumbotron" style="background: transparent;padding: 0 10px;">
          <h2>{{tool.name | title}}</h2>
          <h3>{{tool.code}}</h3>
          <p>{{tool.description}}</p>
          <!--<p>
            <a href="#" class="btn btn-primary" role="button">
              <span class="glyphicon glyphicon-send" aria-hidden="true"></span> 
              Send request
            </a>
          </p>-->
          <h4 style="font-weight: bold">Pickup Address</h4>
          <h5>{{ pickup_address }}</h5>

        {% if pickup_times %}
            <h4 style="font-weight: bold">Pick up time</h4>
            <h5>{{pickup_times.0}} between {{pickup_times.1}}</h5>
        {% endif %}
          {% if not message %}
          <p>
              <form action="" method="POST" name="requestForm">{% csrf_token %}
                <button type="submit" class="btn btn-primary" id="tbn-tool-detail">
                    <span class="glyphicon glyphicon-send" aria-hidden="true"></span> Send request
                </button>
              </form>
          </p>
          {% endif %}
        </div>
      </div>
      </div>

      {% include 'tool_listing/review.html' %}

      {% else %}
      <div class="row">
        <div class="col-md-12">
            <h1 class="bs-callout-danger bs-callout">{{ not_found }}</h1>
        </div>
    {% endif %}
    </div>
  </div>
{% endblock %}

implementation/tool_sharing/templates/tool_listing/tool_detail_modal.html
<div class="modal fade" id="toolDetailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog custom-modal-width" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please Review Tool Information</h4>
      </div>
      <div class="modal-body">
          {% csrf_token %}
          <span id="request-url" class="hide"></span>
          <span id="tool-id" class="hide"></span>
          <div class="container-fluid">
              <div class="row" id="row-content">
                  <!-- Big centered image -->
                  <div class="col-md-4">
                    <div>
                      <a href="#" class="thumbnail" id="link-img" target="_blank">
                        <img id="tool-img" src="" alt="">
                      </a>
                    </div>
                  </div>
                  <!-- /Big centered image -->

                  <!-- the tool information -->
                  <div class="col-md-8">
                    <div class="jumbotron" style="background: transparent;padding: 0 10px;">
                      <h2 id="tool-name"></h2>
                      <h3 id="tool-code"></h3>
                      <p id="tool-description"></p>
                      <h4 style="font-weight: bold">Pickup Address</h4>
                      <h5 id="pu-address"></h5>
                      <div id="pick-up-time-div">
                        <h4 style="font-weight: bold">Pick up time</h4>
                        <h5><span id="pu-days"></span> between <span id="pu-hours"></span></h5>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="alert alert-danger custom-alert-2 hide" role="alert"><strong id="msg-error"></strong></div>
          </div>


      </div>
      <div id="modal-footer" class="modal-footer text-align-center custom-padding">
          <div class="row hide" id="msg-part">
              <div class="col-sm-12">
                  <div class="alert alert-success custom-alert" role="alert" id="msg-ok"></div>
              </div>
          </div>
            <div id="form-part" class="custom-button">
                <button class="btn btn-primary" id="confirm-request">
                    <input type="hidden" value="json" name="format">
                    <span class="glyphicon glyphicon-send" aria-hidden="true"></span> Send request
                </button>
            </div>
      </div>
    </div>
  </div>
</div>